// Date: 8/4/2013 9:26:07 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package fyresmodjam.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTrap2 extends ModelBase
{
    ModelRenderer Shape1, Shape22, Shape26, Shape30, Shape27;

    public ModelTrap2()
    {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 0, 6);
        Shape1.addBox(0F, 0F, 0F, 14, 1, 14);
        Shape1.setRotationPoint(-7F, 23F, -7F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape22 = new ModelRenderer(this, 0, 0);
        Shape22.addBox(0F, 0F, 0F, 3, 2, 1);
        Shape22.setRotationPoint(-2.033333F, 21F, -2F);
        Shape22.setTextureSize(64, 32);
        Shape22.mirror = true;
        setRotation(Shape22, 0F, 0F, 0F);
        Shape26 = new ModelRenderer(this, 0, 0);
        Shape26.addBox(0F, 0F, 0F, 1, 2, 4);
        Shape26.setRotationPoint(1F, 21F, -2F);
        Shape26.setTextureSize(64, 32);
        Shape26.mirror = true;
        setRotation(Shape26, 0F, 0F, 0F);
        Shape30 = new ModelRenderer(this, 0, 0);
        Shape30.addBox(0F, 0F, 0F, 3, 2, 1);
        Shape30.setRotationPoint(-2.033333F, 21F, 1F);
        Shape30.setTextureSize(64, 32);
        Shape30.mirror = true;
        setRotation(Shape30, 0F, 0F, 0F);
        Shape27 = new ModelRenderer(this, 0, 0);
        Shape27.addBox(0F, 0F, 0F, 1, 2, 2);
        Shape27.setRotationPoint(-2F, 21F, -1F);
        Shape27.setTextureSize(64, 32);
        Shape27.mirror = true;
        setRotation(Shape27, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape22.render(f5);
        Shape26.render(f5);
        Shape30.render(f5);
        Shape27.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
